export const TECH_LINKS: Record<string, string> = {
    // Gen AI & NLP
    'LangChain': 'https://www.langchain.com/',
    'LangSmith': 'https://www.langchain.com/langsmith',
    'RAG': 'https://docs.langchain.com/oss/python/langchain/rag',
    'Ragas': 'https://docs.ragas.io/',
    'Hugging Face': 'https://huggingface.co/',
    'OpenAI': 'https://openai.com/',
    'Claude': 'https://www.anthropic.com/claude',
    'Gemini': 'https://deepmind.google/technologies/gemini/',
    'Llama': 'https://llama.meta.com/',
    'DeepSeek': 'https://www.deepseek.com/',
    'Qwen': 'https://github.com/QwenLM/Qwen',
    'Multi-Agent': 'https://cloud.google.com/discover/what-is-a-multi-agent-system',
    'RL': 'https://en.wikipedia.org/wiki/Reinforcement_learning',
    'GRPO': 'https://arxiv.org/abs/2402.03300',
    'Fine-Tuning': 'https://www.ibm.com/es-es/think/topics/fine-tuning',
    'Prompt Engineering': 'https://platform.claude.com/docs/en/build-with-claude/prompt-engineering/claude-prompting-best-practices',
    'AI Guardrails': 'https://pypi.org/project/guardrails-ai/',

    // Programming & Theory
    'Python': 'https://www.python.org/',
    'Rust': 'https://www.rust-lang.org/',
    'SQL': 'https://en.wikipedia.org/wiki/SQL',
    'Java': 'https://www.java.com/',
    'C++': 'https://isocpp.org/',
    'PyTorch': 'https://pytorch.org/',
    'TensorFlow': 'https://www.tensorflow.org/',
    'NumPy': 'https://numpy.org/',
    'Pandas': 'https://pandas.pydata.org/',
    'Algorithm Design': 'https://en.wikipedia.org/wiki/Big_O_notation',
    'Linear Algebra': 'https://en.wikipedia.org/wiki/Linear_algebra',
    'Statistical Analysis': 'https://en.wikipedia.org/wiki/Statistics',
    'Project Management': 'https://en.wikipedia.org/wiki/Project_management',

    // Cloud & MLOps
    'AWS': 'https://aws.amazon.com/',
    'AWS CDK': 'https://aws.amazon.com/cdk/',
    'Azure': 'https://azure.microsoft.com/',
    'GCP': 'https://cloud.google.com/',
    'GitHub Actions': 'https://github.com/features/actions',
    'Docker': 'https://www.docker.com/',
    'Kubernetes': 'https://kubernetes.io/',
    'CI/CD': 'https://about.gitlab.com/topics/ci-cd/',
    'MLflow': 'https://mlflow.org/',
    'Redis': 'https://redis.io/',
    'Pinecone': 'https://www.pinecone.io/',
    'FAISS': 'https://faiss.ai/',
    'Elasticsearch': 'https://www.elastic.co/elasticsearch/',

    // Engineering & Lifecycle
    'SDLC': 'https://en.wikipedia.org/wiki/Systems_development_life_cycle',
    'POC to MVP': 'https://www.coherentsolutions.com/insights/proof-of-concept-prototype-and-mvp-product-validation-stages-explained',
    'Security Protocols': 'https://en.wikipedia.org/wiki/Network_security_policy',
    'System Design': 'https://en.wikipedia.org/wiki/Systems_design',
    'Refactoring': 'https://refactoring.guru/',
    'Parallelization': 'https://en.wikipedia.org/wiki/Parallel_computing',
    'Hadoop': 'https://hadoop.apache.org/',
    'Latency Reduction': 'https://en.wikipedia.org/wiki/Latency_(engineering)',
    'Agile': 'https://www.agilealliance.org/agile101/',
    'Trello': 'https://trello.com/',
    'Streamlit': 'https://streamlit.io/',
    'Tableau': 'https://www.tableau.com/'
};
